#!/bin/bash
git clone https://github.com/spring-projects/spring-boot.git
git clone https://github.com/eugenp/tutorials.git
git clone https://github.com/elastic/elasticsearch.git
git clone https://github.com/zxing/zxing.git
git clone https://github.com/Blankj/AndroidUtilCode.git
git clone https://github.com/square/okhttp.git
git clone https://github.com/PhilJay/MPAndroidChart.git
git clone https://github.com/Snailclimb/JavaGuide.git
git clone https://github.com/google/guava.git
git clone https://github.com/arduino/Arduino.git
git clone https://github.com/nostra13/Android-Universal-Image-Loader.git
git clone https://github.com/ReactiveX/RxJava.git
git clone https://github.com/kdn251/interviews.git
git clone https://github.com/shuzheng/zheng.git
git clone https://github.com/apache/kafka.git
git clone https://github.com/libgdx/libgdx.git
git clone https://github.com/aporter/coursera-android.git
git clone https://github.com/alibaba/druid.git
git clone https://github.com/jfeinstein10/SlidingMenu.git
git clone https://github.com/aosp-mirror/platform_frameworks_base.git
git clone https://github.com/apache/hadoop.git
git clone https://github.com/jenkins-docs/simple-java-maven-app.git
git clone https://github.com/chanjarster/weixin-java-tools.git
git clone https://github.com/jenkinsci/jenkins.git
git clone https://github.com/chrisbanes/Android-PullToRefresh.git
git clone https://github.com/udacity/Sunshine-Version-2.git
git clone https://github.com/bumptech/glide.git
git clone https://github.com/alibaba/fastjson.git
git clone https://github.com/udacity/ud839_Miwok.git
git clone https://github.com/deeplearning4j/deeplearning4j.git
git clone https://github.com/loopj/android-async-http.git
git clone https://github.com/JakeWharton/ViewPagerIndicator.git
git clone https://github.com/greenrobot/EventBus.git
git clone https://github.com/purplecabbage/phonegap-plugins.git
git clone https://github.com/hussien89aa/AndroidTutorialForBeginners.git
git clone https://github.com/ctripcorp/apollo.git
git clone https://github.com/TheAlgorithms/Java.git
git clone https://github.com/apache/flink.git
git clone https://github.com/JakeWharton/ActionBarSherlock.git
git clone https://github.com/airbnb/lottie-android.git
git clone https://github.com/proxyee-down-org/proxyee-down.git
git clone https://github.com/google/ExoPlayer.git
git clone https://github.com/commonsguy/cw-omnibus.git
git clone https://github.com/bigbluebutton/bigbluebutton.git
git clone https://github.com/facebook/fresco.git
git clone https://github.com/Activiti/Activiti.git
git clone https://github.com/forezp/SpringCloudLearning.git
git clone https://github.com/spring-projects/spring-mvc-showcase.git
git clone https://github.com/code4craft/webmagic.git
git clone https://github.com/scwang90/SmartRefreshLayout.git
git clone https://github.com/Netflix/Hystrix.git
git clone https://github.com/square/leakcanary.git
git clone https://github.com/apache/camel.git
git clone https://github.com/lhazlewood/apache-shiro-tutorial-webapp.git
git clone https://github.com/spring-projects/spring-security-oauth.git
git clone https://github.com/MyCATApache/Mycat-Server.git
git clone https://github.com/mission-peace/interview.git
git clone https://github.com/springside/springside4.git
git clone https://github.com/android10/Android-CleanArchitecture.git
git clone https://github.com/wyouflf/xUtils.git
git clone https://github.com/xetorthio/jedis.git
git clone https://github.com/prestodb/presto.git
git clone https://github.com/spring-projects/spring-security.git
git clone https://github.com/xuxueli/xxl-job.git
git clone https://github.com/astuetz/PagerSlidingTabStrip.git
git clone https://github.com/survivingwithandroid/Surviving-with-android.git
git clone https://github.com/ReactiveX/RxAndroid.git
git clone https://github.com/sqshq/piggymetrics.git
git clone https://github.com/alibaba/canal.git
git clone https://github.com/square/dagger.git
git clone https://github.com/apereo/cas.git
git clone https://github.com/naver/pinpoint.git
git clone https://github.com/androidannotations/androidannotations.git
git clone https://github.com/LMAX-Exchange/disruptor.git
git clone https://github.com/DroidPluginTeam/DroidPlugin.git
git clone https://github.com/dyc87112/SpringBoot-Learning.git
git clone https://github.com/googlemaps/android-samples.git
git clone https://github.com/apache/incubator-shardingsphere.git
git clone https://github.com/googlesamples/google-services.git
git clone https://github.com/runelite/runelite.git
git clone https://github.com/hongyangAndroid/okhttputils.git
git clone https://github.com/openmrs/openmrs-core.git
git clone https://github.com/googlesamples/android-testing.git
git clone https://github.com/liferay/liferay-portal.git
git clone https://github.com/careercup/ctci.git
git clone https://github.com/apache/cassandra.git
git clone https://github.com/umano/AndroidSlidingUpPanel.git
git clone https://github.com/stleary/JSON-java.git
git clone https://github.com/daimajia/AndroidViewAnimations.git
git clone https://github.com/elasticjob/elastic-job-lite.git
git clone https://github.com/jeasonlzy/okhttp-OkGo.git
git clone https://github.com/liferay/liferay-plugins.git
git clone https://github.com/googlesamples/android-play-location.git
git clone https://github.com/vondear/RxTool.git
git clone https://github.com/hs-web/hsweb-framework.git
git clone https://github.com/aws/aws-sdk-java.git
git clone https://github.com/knightliao/disconf.git
git clone https://github.com/motianhuo/wechat.git
git clone https://github.com/yixia/VitamioBundle.git
git clone https://github.com/stanfordnlp/CoreNLP.git
