#!/bin/bash

git clone https://github.com/apache/accumulo.git accumulo
git clone https://github.com/apache/accumulo.git accumulo_old
git clone https://github.com/apache/ant.git ant
git clone https://github.com/apache/ant.git ant_old 
git clone https://github.com/antlr/antlr4.git antlr4
git clone https://github.com/antlr/antlr4.git antlr4_old
git clone https://github.com/bitcoinj/bitcoinj.git bitcoinj
git clone https://github.com/bitcoinj/bitcoinj.git bitcoinj_old
git clone https://github.com/checkstyle/checkstyle.git checkstyle
git clone https://github.com/checkstyle/checkstyle.git checkstyle_old
git clone https://github.com/google/closure-compiler.git closure-compiler
git clone https://github.com/google/closure-compiler.github closure-compiler_old
git clone https://github.com/deeplearning4j/deeplearning4j.git deeplearning4j
git clone https://github.com/deeplearning4j/deeplearning4j.git deeplearning4j_old
git clone https://github.com/apache/drill.git drill
git clone https://github.com/apache/drill.git drill_old
git clone https://github.com/apache/eagle.git eagle
git clone https://github.com/apache/eagle.git eagle_old
git clone https://github.com/google/error-prone.git error-prone
git clone https://github.com/google/error-prone.git error-prone_old
git clone https://github.com/google/ExoPlayer.git ExoPlayer
git clone https://github.com/google/ExoPlayer.git ExoPlayer_old
git clone https://github.com/fabric8io/fabric8.git fabric8
git clone https://github.com/fabric8io/fabric8.git fabric8_old
git clone https://github.com/apache/giraph.git giraph
git clone https://github.com/apache/giraph.git giraph_old
git clone https://github.com/google/gson.git gson
git clone https://github.com/google/gson.git gson_old
git clone https://github.com/google/guava.git guava
git clone https://github.com/google/guava.git guava_old
git clone https://github.com/spotify/helios.git helios
git clone https://github.com/spotify/helios.git helios_old
git clone https://github.com/apache/hive.git hive
git clone https://github.com/apache/hive.git hive_old
git clone https://github.com/jboss-developer/jboss-eap-quickstarts.git jboss-eap-quickstarts
git clone https://github.com/jboss-developer/jboss-eap-quickstarts.git jboss-eap-quickstarts_old
git clone https://github.com/eclipse/jetty.project.git jetty.project
git clone https://github.com/eclipse/jetty.project.git jetty.project_old
git clone https://github.com/kevinsawicki/github-maven-example.git maven
git clone https://github.com/kevinsawicki/github-maven-example.git maven_old
git clone https://github.com/openhab/openhab1-addons.git openhab1-addons
git clone https://github.com/openhab/openhab1-addons.git openhab1-addons_old
git clone https://github.com/orientechnologies/orientdb.git orientdb
git clone https://github.com/orientechnologies/orientdb.git orientdb_old
git clone https://github.com/facebook/presto.git presto                                                   
git clone https://github.com/facebook/presto.git presto_old
git clone https://github.com/querydsl/querydsl.git querydsl
git clone https://github.com/querydsl/querydsl.git querydsl_old
git clone https://github.com/mrniko/redisson.git redisson
git clone https://github.com/mrniko/redisson.git redisson_old
git clone https://github.com/spring-projects/spring-roo.git spring-roo
git clone https://github.com/spring-projects/spring-roo.git spring-roo_old
git clone https://github.com/structr/structr.git structr
git clone https://github.com/structr/structr.git structr_old
git clone https://github.com/google/truth.git truth
git clone https://github.com/google/truth.git truth_old