#!/bin/bash

git clone https://github.com/JetBrains/intellij-community.git
git clone https://github.com/JetBrains/MPS.git
git clone https://github.com/CyanogenMod/android_frameworks_base.git
git clone https://github.com/liferay/liferay-plugins.git
git clone https://github.com/neo4j/neo4j.git
git clone https://github.com/apache/camel.git
git clone https://github.com/gradle/gradle.git
git clone https://github.com/processing/processing.git
git clone https://github.com/elastic/elasticsearch.git
git clone https://github.com/belaban/JGroups.git
git clone https://github.com/osmandapp/Osmand.git
git clone https://github.com/wildfly/wildfly.git
git clone https://github.com/SonarSource/sonarqube.git
git clone https://github.com/VoltDB/voltdb.git
git clone https://github.com/languagetool-org/languagetool.git
git clone https://github.com/grails/grails-core.git
git clone https://github.com/apache/hive.git
git clone https://github.com/fabric8io/fabric8.git
git clone https://github.com/hazelcast/hazelcast.git
git clone https://github.com/apache/cassandra.git
git clone https://github.com/rstudio/rstudio.git
git clone https://github.com/spring-projects/spring-framework.git
git clone https://github.com/droolsjbpm/drools.git
git clone https://github.com/BroadleafCommerce/BroadleafCommerce.git
git clone https://github.com/eclipse/jetty.project.git
git clone https://github.com/restlet/restlet-framework-java.git
git clone https://github.com/orientechnologies/orientdb.git
git clone https://github.com/gwtproject/gwt.git
git clone https://github.com/hibernate/hibernate-orm.git
git clone https://github.com/infinispan/infinispan.git
git clone https://github.com/libgdx/libgdx.git
git clone https://github.com/wordpress-mobile/WordPress-Android.git
git clone https://github.com/opentripplanner/OpenTripPlanner.git
git clone https://github.com/spring-projects/spring-integration.git
git clone https://github.com/cgeo/cgeo.git
git clone https://github.com/JetBrains/intellij-plugins.git
git clone https://github.com/k9mail/k-9.git
git clone https://github.com/querydsl/querydsl.git
git clone https://github.com/checkstyle/checkstyle.git
git clone https://github.com/geoserver/geoserver.git
git clone https://github.com/Jasig/cas.git
git clone https://github.com/facebook/presto.git
git clone https://github.com/openhab/openhab.git
git clone https://github.com/google/closure-compiler.git
git clone https://github.com/Activiti/Activiti.git
git clone https://github.com/mongodb/mongo-java-driver.git
git clone https://github.com/structr/structr.git
git clone https://github.com/jMonkeyEngine/jmonkeyengine.git
git clone https://github.com/crate/crate.git
git clone https://github.com/spring-projects/spring-roo.git
git clone https://github.com/spring-projects/spring-boot.git
git clone https://github.com/Graylog2/graylog2-server.git
git clone https://github.com/MovingBlocks/Terasology.git
git clone https://github.com/amplab/tachyon.git
git clone https://github.com/facebook/buck.git
git clone https://github.com/deeplearning4j/deeplearning4j.git
git clone https://github.com/plutext/docx4j.git
git clone https://github.com/open-keychain/open-keychain.git
git clone https://github.com/jOOQ/jOOQ.git
git clone https://github.com/jboss-developer/jboss-eap-quickstarts.git
git clone https://github.com/wicketstuff/core.git
git clone https://github.com/droolsjbpm/jbpm.git
git clone https://github.com/ratpack/ratpack.git
git clone https://github.com/google/j2objc.git
git clone https://github.com/antlr/antlr4.git
git clone https://github.com/BuildCraft/BuildCraft.git
git clone https://github.com/go-lang-plugin-org/go-lang-idea-plugin.git
git clone https://github.com/realm/realm-java.git
git clone https://github.com/oblac/jodd.git
git clone https://github.com/SecUpwN/Android-IMSI-Catcher-Detector.git
git clone https://github.com/bitcoinj/bitcoinj.git
git clone https://github.com/mockito/mockito.git
git clone https://github.com/abarisain/dmix.git
git clone https://github.com/SlimeKnights/TinkersConstruct.git
git clone https://github.com/real-logic/Aeron.git
git clone https://github.com/cbeust/testng.git
git clone https://github.com/glyptodon/guacamole-client.git
git clone https://github.com/github/android.git
git clone https://github.com/apache/drill.git
git clone https://github.com/puniverse/quasar.git
git clone https://github.com/robovm/robovm.git
git clone https://github.com/FasterXML/jackson-databind.git
git clone https://github.com/siacs/Conversations.git
git clone https://github.com/spotify/helios.git
git clone https://github.com/cwensel/cascading.git
git clone https://github.com/AntennaPod/AntennaPod.git
git clone https://github.com/addthis/hydra.git
git clone https://github.com/datastax/java-driver.git
git clone https://github.com/WhisperSystems/TextSecure.git
git clone https://github.com/jersey/jersey.git
git clone https://github.com/spring-projects/spring-data-neo4j.git
git clone https://github.com/brettwooldridge/HikariCP.git
git clone https://github.com/ignatov/intellij-erlang.git
git clone https://github.com/mongodb/morphia.git
git clone https://github.com/jenkinsci/workflow-plugin.git
git clone https://github.com/kuujo/copycat.git
git clone https://github.com/GoClipse/goclipse.git
git clone https://github.com/raphw/byte-buddy.git
git clone https://github.com/Netflix/eureka.git
git clone https://github.com/rackerlabs/blueflood.git
git clone https://github.com/xetorthio/jedis.git
git clone https://github.com/jayway/rest-assured.git
git clone https://github.com/linkedin/rest.li.git
git clone https://github.com/joel-costigliola/assertj-core.git
git clone https://github.com/baasbox/baasbox.git
git clone https://github.com/RoboBinding/RoboBinding.git
git clone https://github.com/apache/giraph.git
git clone https://github.com/spring-projects/spring-data-rest.git
git clone https://github.com/redsolution/xabber-android.git
git clone https://github.com/loopj/android-async-http.git
git clone https://github.com/mrniko/redisson.git
git clone https://github.com/google/truth.git
git clone https://github.com/phishman3579/java-algorithms-implementation.git
git clone https://github.com/hierynomus/sshj.git
git clone https://github.com/Netflix/zuul.git
git clone https://github.com/scobal/seyren.git
git clone https://github.com/aws/aws-sdk-java.git
git clone https://github.com/orfjackal/retrolambda.git
git clone https://github.com/square/javapoet.git
git clone https://github.com/zeromq/jeromq.git
git clone https://github.com/bitfireAT/davdroid.git
git clone https://github.com/bennidi/mbassador.git
git clone https://github.com/novoda/android-demos.git
git clone https://github.com/jfinal/jfinal.git